# Generated by Django 5.2.8 on 2025-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0003_whishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
