# Generated by Django 5.2.8 on 2025-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0004_mycart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
